app {
  inputFile = "sample-data/small_events.jsonl"
  outputDir = "out"
  emailSalt = ${?EMAIL_SALT}
  inputMode = "file"
  inputMode = ${?APP_INPUT_MODE}
  streamDelayMillis = 0
  streamDelayMillis = ${?APP_STREAM_DELAY_MILLIS}
}

postgres {
  host = "localhost"
  port = ${?POSTGRES_PORT}
  database = ${?POSTGRES_DB}
  user = ${?POSTGRES_USER}
  password = ${?POSTGRES_PASSWORD}
  driver = "org.postgresql.Driver"
}

mongo {
  host = "localhost"
  port = ${?MONGO_PORT}
  database = ${?MONGO_DATABASE}
  processedCollection = "processed_transactions"
  alertsCollection = "alerts"
  violationsCollection = "eligibility_violations"
}

kafka {
  bootstrapServers = "localhost:19092"
  bootstrapServers = ${?KAFKA_BOOTSTRAP_SERVERS}
  topic = "payment-events"
  topic = ${?KAFKA_TOPIC}
  groupId = "payment-event-pipeline"
  groupId = ${?KAFKA_GROUP_ID}
  clientId = "payment-event-pipeline-local"
  clientId = ${?KAFKA_CLIENT_ID}
}
