app {
  inputFile = "sample-data/small_events.jsonl"
  outputDir = "out"
  emailSalt = ${?EMAIL_SALT}
  inputMode = "file"
  streamDelayMillis = 0
}

postgres {
  host = "localhost"
  port = ${?POSTGRES_PORT}
  database = ${?POSTGRES_DB}
  user = ${?POSTGRES_USER}
  password = ${?POSTGRES_PASSWORD}
  driver = "org.postgresql.Driver"
}

mongo {
  host = "localhost"
  port = ${?MONGO_PORT}
  database = ${?MONGO_DATABASE}
  processedCollection = "processed_transactions"
  alertsCollection = "alerts"
  violationsCollection = "eligibility_violations"
}
